In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [ ]:
file_path = "/content/Response.csv"
df = pd.read_csv(file_path)

In [ ]:
df = pd.read_csv("/content/Response.csv")

In [ ]:
# Apply one-hot encoding to the age column
df = pd.get_dummies(df, columns=['Age'])

# Display the preprocessed dataset
print(df.head())


   Gender diagnosed with depression  symptoms of depression frequency  \
0  Female                       Yes                                 3   
1  Female                     Maybe                                 3   
2    Male                       Yes                                 5   
3    Male                       Yes                                 2   
4    Male                       Yes                                 5   

  professional help or counseling for depression  \
0                                            Yes   
1                                            Yes   
2                                             No   
3                                            Yes   
4                                            Yes   

  feel stressed due to academic workload engage in stress-relief activities  \
0                             Frequently                                 No   
1                             Constantly                                 No   
2          

In [ ]:
df[['Age_18-21','Age_22-25', 'Age_26-30', 'Age_Under 18']] = df[['Age_18-21','Age_22-25', 'Age_26-30', 'Age_Under 18']].astype(int)
print(df.head())


   Gender diagnosed with depression  symptoms of depression frequency  \
0  Female                       Yes                                 3   
1  Female                     Maybe                                 3   
2    Male                       Yes                                 5   
3    Male                       Yes                                 2   
4    Male                       Yes                                 5   

  professional help or counseling for depression  \
0                                            Yes   
1                                            Yes   
2                                             No   
3                                            Yes   
4                                            Yes   

  feel stressed due to academic workload engage in stress-relief activities  \
0                             Frequently                                 No   
1                             Constantly                                 No   
2          

In [ ]:
# Apply one-hot encoding to the gender column
df = pd.get_dummies(df, columns=['Gender'])

# Display the preprocessed dataset
print(df.head())


  diagnosed with depression  symptoms of depression frequency  \
0                       Yes                                 3   
1                     Maybe                                 3   
2                       Yes                                 5   
3                       Yes                                 2   
4                       Yes                                 5   

  professional help or counseling for depression  \
0                                            Yes   
1                                            Yes   
2                                             No   
3                                            Yes   
4                                            Yes   

  feel stressed due to academic workload engage in stress-relief activities  \
0                             Frequently                                 No   
1                             Constantly                                 No   
2                              Sometimes                   

In [ ]:
df[['Gender_Female', 'Gender_Male', 'Gender_Prefer not to say']] = df[['Gender_Female', 'Gender_Male', 'Gender_Prefer not to say']].astype(int)
print(df.head())


  diagnosed with depression  symptoms of depression frequency  \
0                       Yes                                 3   
1                     Maybe                                 3   
2                       Yes                                 5   
3                       Yes                                 2   
4                       Yes                                 5   

  professional help or counseling for depression  \
0                                            Yes   
1                                            Yes   
2                                             No   
3                                            Yes   
4                                            Yes   

  feel stressed due to academic workload engage in stress-relief activities  \
0                             Frequently                                 No   
1                             Constantly                                 No   
2                              Sometimes                   

In [ ]:
# Define a dictionary to map categories to numerical values
diagnosis_mapping = {'No': 0, 'Maybe': 1, 'Yes': 2}

# Apply mapping to the 'diagnosed with depression' column
df['diagnosed with depression'] = df['diagnosed with depression'].map(diagnosis_mapping)

# Display the preprocessed dataset
print(df.head())



   diagnosed with depression  symptoms of depression frequency  \
0                          2                                 3   
1                          1                                 3   
2                          2                                 5   
3                          2                                 2   
4                          2                                 5   

  professional help or counseling for depression  \
0                                            Yes   
1                                            Yes   
2                                             No   
3                                            Yes   
4                                            Yes   

  feel stressed due to academic workload engage in stress-relief activities  \
0                             Frequently                                 No   
1                             Constantly                                 No   
2                              Sometimes             

In [ ]:
# Remove leading/trailing whitespace and convert to lowercase
df['technology (e.g., NLP and HCI) can positively impact mental wellness'] = df['technology (e.g., NLP and HCI) can positively impact mental wellness'].str.strip().str.lower()

# Replace values and capitalize 'Maybe'
df['technology (e.g., NLP and HCI) can positively impact mental wellness'].replace({'maybe  ': 'Maybe', 'yes': 'Yes', 'no': 'No'}, inplace=True)

# Capitalize 'Maybe'
df['technology (e.g., NLP and HCI) can positively impact mental wellness'] = df['technology (e.g., NLP and HCI) can positively impact mental wellness'].apply(lambda x: x.title())

# Check unique values after replacement
print("Unique values after replacement:", df['technology (e.g., NLP and HCI) can positively impact mental wellness'].unique())


Unique values after replacement: ['Maybe' 'Yes' 'No']


In [ ]:
# Define a dictionary to map categories to numerical values
technology_mapping = {'No': 0, 'Maybe': 1, 'Yes': 2}

# Apply mapping to the 'technology (e.g., NLP and HCI) can positively impact mental wellness' column
df['technology (e.g., NLP and HCI) can positively impact mental wellness'] = df['technology (e.g., NLP and HCI) can positively impact mental wellness'].map(diagnosis_mapping)



In [ ]:
print(df['technology (e.g., NLP and HCI) can positively impact mental wellness'].unique())


[1 2 0]


In [ ]:
# Define a dictionary to map categories to numerical values
mapping = {'No': 0, 'Maybe': 1, 'Yes': 2}

# Apply mapping to the 'diagnosed with depression' column
df['open to use technology based solutions to manage mental health'] = df['open to use technology based solutions to manage mental health'].map(mapping)



print(df['open to use technology based solutions to manage mental health'].unique())


[1 0 2]


In [ ]:
# Replace "Maybe " with "Maybe" in the column
df['interested in participating in workshops or programs'] = df['interested in participating in workshops or programs'].replace('Maybe ', 'Maybe')




In [ ]:
# Define a dictionary to map categories to numerical values
mapping = {'No': 0, 'Maybe': 1, 'Yes': 2}

# Apply mapping to the 'diagnosed with depression' column
df['interested in participating in workshops or programs'] = df['interested in participating in workshops or programs'].map(mapping)
print(df['interested in participating in workshops or programs'].unique())

[1 2 0]


In [ ]:
print(df['Preference to access mental health resources and information'].unique())

['Mobile apps or online platforms' 'Both'
 'In-person workshops and counseling'
 'Haven’t used any specific resources.' "Don't know" 'By myself'
 'In-person workshops' 'Both ' 'Mobile apps or online platforms ']


In [ ]:
# Define a dictionary to map categories to numerical values
mapping = {'No': 0, 'Sometimes': 1, 'Yes': 2}

# Apply mapping to the 'diagnosed with depression' column
df['comfort in discussing mental health with friends or family'] = df['comfort in discussing mental health with friends or family'].map(mapping)


print(df['comfort in discussing mental health with friends or family'].unique())


[0 2 1]


In [ ]:
# Convert column values to lowercase and remove leading/trailing whitespaces
df['professional help or counseling for depression'] = df['professional help or counseling for depression'].str.strip().str.lower()

# Map 'yes' to 'Yes' and 'no' to 'No ' (with a trailing whitespace)
df['professional help or counseling for depression'] = df['professional help or counseling for depression'].map({'no': 'No', 'yes': 'Yes'})

In [ ]:
# # Display the preprocessed dataset
# print(df.head())

# Check unique values in the 'professional help or counseling for depression' column
print(df['professional help or counseling for depression'].unique())

# Map 'yes' to 1, 'no' to 0, and handle NaN values
df['professional help or counseling for depression'] = df['professional help or counseling for depression'].map({'No': 0, 'Yes': 1})

# # Display the preprocessed dataset
print(df.head())

['Yes' 'No']
   diagnosed with depression  symptoms of depression frequency  \
0                          2                                 3   
1                          1                                 3   
2                          2                                 5   
3                          2                                 2   
4                          2                                 5   

   professional help or counseling for depression  \
0                                               1   
1                                               1   
2                                               0   
3                                               1   
4                                               1   

  feel stressed due to academic workload engage in stress-relief activities  \
0                             Frequently                                 No   
1                             Constantly                                 No   
2                              Som

In [ ]:
df['facing discrimination related to your mental health issues'] = df['facing discrimination related to your mental health issues'].map({'No': 0, 'Yes': 1})

print(df['facing discrimination related to your mental health issues'].unique())


[1 0]


In [ ]:
df['engage in stress-relief activities'] = df['engage in stress-relief activities'].replace('yes', 'Yes')

# Map 'yes' to 1 and 'no' to 0 in the 'engage in stress-relief activities' column
df['engage in stress-relief activities'] = df['engage in stress-relief activities'].map({'No': 0, 'Yes': 1})

# Display the preprocessed dataset
print(df.head())
print(df['engage in stress-relief activities'].unique())


   diagnosed with depression  symptoms of depression frequency  \
0                          2                                 3   
1                          1                                 3   
2                          2                                 5   
3                          2                                 2   
4                          2                                 5   

   professional help or counseling for depression  \
0                                               1   
1                                               1   
2                                               0   
3                                               1   
4                                               1   

  feel stressed due to academic workload  engage in stress-relief activities  \
0                             Frequently                                   0   
1                             Constantly                                   0   
2                              Sometimes    

In [ ]:
df['feel pressure to excel academically'] = df['feel pressure to excel academically'].replace('yes', 'Yes')
print(df['feel pressure to excel academically'].unique())

['No' 'Yes']


In [ ]:
df['feel pressure to excel academically'] = df['feel pressure to excel academically'].map({'No': 0, 'Yes': 1})
print(df.head())


   diagnosed with depression  symptoms of depression frequency  \
0                          2                                 3   
1                          1                                 3   
2                          2                                 5   
3                          2                                 2   
4                          2                                 5   

   professional help or counseling for depression  \
0                                               1   
1                                               1   
2                                               0   
3                                               1   
4                                               1   

  feel stressed due to academic workload  engage in stress-relief activities  \
0                             Frequently                                   0   
1                             Constantly                                   0   
2                              Sometimes    

In [ ]:
df['academic counseling or support'] = df['academic counseling or support'].replace({'no': 'No', 'yes': 'Yes'})
print(df['academic counseling or support'].unique())

['No' 'Yes']


In [ ]:
df['academic counseling or support'] = df['academic counseling or support'].map({'No': 0, 'Yes': 1})
print(df.head())

   diagnosed with depression  symptoms of depression frequency  \
0                          2                                 3   
1                          1                                 3   
2                          2                                 5   
3                          2                                 2   
4                          2                                 5   

   professional help or counseling for depression  \
0                                               1   
1                                               1   
2                                               0   
3                                               1   
4                                               1   

  feel stressed due to academic workload  engage in stress-relief activities  \
0                             Frequently                                   0   
1                             Constantly                                   0   
2                              Sometimes    

In [ ]:
df['engaging in self-harming behaviors'] = df['engaging in self-harming behaviors'].map({'No': 0, 'Yes': 1})
print(df.head())

   diagnosed with depression  symptoms of depression frequency  \
0                          2                                 3   
1                          1                                 3   
2                          2                                 5   
3                          2                                 2   
4                          2                                 5   

   professional help or counseling for depression  \
0                                               1   
1                                               1   
2                                               0   
3                                               1   
4                                               1   

  feel stressed due to academic workload  engage in stress-relief activities  \
0                             Frequently                                   0   
1                             Constantly                                   0   
2                              Sometimes    

In [ ]:
# Convert column values to lowercase and remove leading/trailing whitespaces
df['professional help or counseling for self-harm'] = df['professional help or counseling for self-harm'].str.strip().str.lower()

# Check unique values after stripping and lowercasing
print("Unique values before mapping:", df['professional help or counseling for self-harm'].unique())

# Map 'yes' to 'Yes' and 'no' to 'No'
df['professional help or counseling for self-harm'] = df['professional help or counseling for self-harm'].map({'yes': 'Yes', 'no': 'No'})

# Check unique values after mapping
print("Unique values after mapping:", df['professional help or counseling for self-harm'].unique())

# Count null values
null_values_count = df['professional help or counseling for self-harm'].isnull().sum()
print("Number of null values in the column:", null_values_count)


Unique values before mapping: ['no' 'yes']
Unique values after mapping: ['No' 'Yes']
Number of null values in the column: 0


In [ ]:
# Map 'Yes' to 1 and 'No' to 0
df['professional help or counseling for self-harm'] = df['professional help or counseling for self-harm'].map({'Yes': 1, 'No': 0})

# Check unique values after mapping
print("Unique values after mapping:", df['professional help or counseling for self-harm'].unique())


Unique values after mapping: [0 1]


In [ ]:
# Specify the column for which you want to check unique values
column_name = 'feel stressed due to academic workload'  # Replace 'your_column_name' with the name of your column

# Get all unique values in the specified column
unique_values = df[column_name].unique()

# Print the unique values
print(unique_values)


['Frequently' 'Constantly' 'Sometimes' 'Occasionally' 'Rarely']


In [ ]:
# Define a dictionary to map categories to numerical values based on their frequency or intensity
stress_mapping = {'Rarely': 0, 'Occasionally': 1, 'Sometimes': 2, 'Frequently': 3, 'Constantly': 4}

# Apply mapping to the 'feel stressed due to academic workload' column
df['feel stressed due to academic workload'] = df['feel stressed due to academic workload'].map(stress_mapping)

# Display the preprocessed dataset
print(df.head())

   diagnosed with depression  symptoms of depression frequency  \
0                          2                                 3   
1                          1                                 3   
2                          2                                 5   
3                          2                                 2   
4                          2                                 5   

   professional help or counseling for depression  \
0                                               1   
1                                               1   
2                                               0   
3                                               1   
4                                               1   

   feel stressed due to academic workload  engage in stress-relief activities  \
0                                       3                                   0   
1                                       4                                   0   
2                                       2

In [ ]:
# Remove leading/trailing whitespaces from the unique values in the column
df['Supportive academic environment'] = df['Supportive academic environment'].str.strip()


print(df['Supportive academic environment'].unique())


['Extremely Important' 'Important' 'Neutral' 'Not Important'
 'Somewhat Important']


In [ ]:
# Remove leading/trailing whitespace and convert to lowercase
df['Supportive academic environment'] = df['Supportive academic environment'].str.strip().str.lower()

# Map categories to numerical values
environment_mapping = {
    'extremely important': 4,
    'important': 3,
    'neutral': 2,
    'somewhat important': 1,
    'not important': 0
}

df['Supportive academic environment'] = df['Supportive academic environment'].map(environment_mapping)

# Display the preprocessed dataset
print(df['Supportive academic environment'].unique())


[4 3 2 0 1]


In [ ]:
# Remove leading/trailing whitespace and convert to lowercase
df['Peer support groups'] = df['Peer support groups'].str.strip().str.lower()

# Map categories to numerical values
environment_mapping = {
    'extremely important': 4,
    'important': 3,
    'neutral': 2,
    'somewhat important': 1,
    'not important': 0
}

df['Peer support groups'] = df['Peer support groups'].map(environment_mapping)
print(df['Peer support groups'].unique())


[3 2 4 1 0]


In [ ]:
environment_mapping = {
    'Extremely Important': 4,
    'Important': 3,
    'Neutral': 2,
    'Somewhat Important': 1,
    'Not Important': 0
}

df['Mental health awareness campaigns'] = df['Mental health awareness campaigns'].map(environment_mapping)
print(df['Mental health awareness campaigns'].unique())


[4 3 2 1 0]


In [ ]:
df['engaging in activities or hobbies'] = df['engaging in activities or hobbies'].replace('Daily ', 'Daily')

print(df['engaging in activities or hobbies'].unique())


['Several times a week' 'Occasionally' 'Rarely' 'Never' 'Daily']


In [ ]:
# Define a mapping of ordinal values
ordinal_mapping = {
    'Never': 0,
    'Rarely': 1,
    'Occasionally': 2,
    'Several times a week': 3,
    'Daily': 4
}

# Map ordinal values to the column
df['engaging in activities or hobbies'] = df['engaging in activities or hobbies'].map(ordinal_mapping)
print(df['engaging in activities or hobbies'].unique())


[3 2 1 0 4]


In [ ]:
df['accessible counseling services'] = df['accessible counseling services'].str.strip().str.lower()

print(df['accessible counseling services'].unique())


['important' 'not important' 'extremely important' 'neutral'
 'somewhat important']


In [ ]:
environment_mapping = {
    'extremely important': 4,
    'important': 3,
    'neutral': 2,
    'somewhat important': 1,
    'not important': 0
}

df['accessible counseling services'] = df['accessible counseling services'].map(environment_mapping)
print(df['accessible counseling services'].unique())


[3 0 4 2 1]


In [ ]:
print(df.head(50))

    diagnosed with depression  symptoms of depression frequency  \
0                           2                                 3   
1                           1                                 3   
2                           2                                 5   
3                           2                                 2   
4                           2                                 5   
5                           0                                 3   
6                           0                                 1   
7                           2                                 5   
8                           2                                 4   
9                           0                                 1   
10                          1                                 3   
11                          0                                 3   
12                          0                                 3   
13                          1                                 

In [ ]:
# Define the file path for the CSV file
csv_file_path = '/content/post_preprocessed_data.csv'  # Change the path as needed

# Export the DataFrame to a CSV file
df.to_csv(csv_file_path, index=False)  # Set index=False to exclude row numbers from the CSV

# Optionally, display a message indicating that the CSV file has been saved
print("CSV file saved successfully at:", csv_file_path)


CSV file saved successfully at: /content/post_preprocessed_data.csv


In [ ]:
from google.colab import files

files.download(csv_file_path)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>